[package]
name = "documentdb_macros"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "documentdb_macros"
path = "src/lib.rs"
proc-macro = true

[lints]
workspace = true